url: https://www.hotmap.info
#baseurl: /agency-jekyll-theme/

# Site settings
title: Hot Map
email: hotmap2019@gmail.com
description: "The powerful privacy map to search for Adult tourism, Fashion-health clubs, Massages, Room salons, Gogo bars (including ladybody go go bars), LGBT scenes, etc.for a hot and secret night out."
keyword: "Adult tourism, Massages,Â Escorts, Soapies, hostess bar, room salon, Asian bar scene,LGBT Scenes, go go bars, Strip club,Ladyboy gogo bars,P4P Scene, South East Asia Tourism"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty